# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hkxMTrOCuu_icn-LI-UU6prYXSEv-eIj
"""

import sys
import requests
import random
from ui_pruebapyqt5 import *
from PySide2.QtCore import QTimer, QTime

from PySide2.QtWidgets import QMenu, QMessageBox
from PySide2.QtCore import Qt, QEvent

class MiApp(QMainWindow):
    
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        
        
        timer = QTimer(self)
        timer.timeout.connect(self.displayTime)
        timer.start(1000)
        
        self.ui.btnConsultar.clicked.connect(self.clicked)
        self.ui.listWidget.itemClicked.connect(self.itemClicked)
        
        
#    def eventFilter(self, source, event):
#        if event.type() == QEvent.ContextMenu and source is self.listWidget:
#            menu =QMenu()
#            menu.addAction('Informacion del personaje')
#            if menu.exec_(event.globalPos()):
#                item = source.itemAt(event.pos())
#                ##########
#            return True
#        
#        return super().eventFilter(source, event)

    def itemClicked(self):
        msg =QMessageBox()
        msg.setWindowTitle("Ventana Secundaria")
        
        id = self.numeros[self.ui.listWidget.currentRow()]
        #print(id)
        path = 'https://swapi.dev/api/people/' + str(id)
        r = requests.get(path, timeout=10)
        j = r.json()
        datos = 'height: ' + str(j["height"]) + '\nmass: ' + str(j["mass"]) + '\nhair_color: ' + str(j["hair_color"]) + '\nskin_color: ' + str(j["skin_color"]) + '\neye_color: ' + str(j["eye_color"]) + '\nbirth_year: ' + str(j["birth_year"]) + '\ngender: ' + str(j["gender"])
        msg.setText(datos)
        #print(str(j["name"]))
        x = msg.exec()
        
        
    def clicked(self):
        val = list(range(1, 84))
        self.numeros = random.sample(val, 10)
        k = 0;
        self.ui.listWidget.clear()
        for i in self.numeros:      
            path = 'https://swapi.dev/api/people/' + str(i)
            r = requests.get(path, timeout=10)
            j = r.json()
            #print(j["name"])
            self.ui.listWidget.insertItem(k, str(j["name"]))
            k = k + 1
            

    def displayTime(self):
        currentTime = QTime.currentTime()
        currentDate = QDate.currentDate()
        hora = currentTime.toString('hh:mm:ss')
        fecha = currentDate.toString(Qt.DefaultLocaleShortDate)
        self.ui.lblHora.setText(hora)
        self.ui.lblFecha.setText((fecha.upper()))
        
if __name__ == "__main__":
     app = QApplication(sys.argv)
     mi_app = MiApp()
     mi_app.show()
     sys.exit(app.exec_())
